spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888/"

# Minimal local config, remainder in Config Server
server:
  port: 8081

logging:
  level:
    com.ecommerce.auth: DEBUG
