spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888/"

# Minimal local config, remainder in Config Server
server:
  port: 8082

logging:
  level:
    com.ecommerce.product: DEBUG
